version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
    - "2181:2181"
    networks:
    - kafka-network
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka0:
    image: confluentinc/cp-kafka
    ports:
    - "9092:9092"
    networks:
    - kafka-network
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL_LISTENER://kafka0:29092,EXTERNAL_LISTENER://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL_LISTENER:PLAINTEXT,EXTERNAL_LISTENER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL_LISTENER
      KAFKA_BROKER_ID: 0
    container_name: kafka0
    depends_on:
    - zookeeper
  kafka1:
    image: confluentinc/cp-kafka
    ports:
    - "9093:9093"
    networks:
    - kafka-network
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL_LISTENER://kafka1:29092,EXTERNAL_LISTENER://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL_LISTENER:PLAINTEXT,EXTERNAL_LISTENER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL_LISTENER
      KAFKA_BROKER_ID: 1
    container_name: kafka1
    depends_on:
    - zookeeper
  kafka2:
    image: confluentinc/cp-kafka
    ports:
    - "9094:9094"
    networks:
    - kafka-network
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL_LISTENER://kafka2:29092,EXTERNAL_LISTENER://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL_LISTENER:PLAINTEXT,EXTERNAL_LISTENER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL_LISTENER
      KAFKA_BROKER_ID: 2
    container_name: kafka2
    depends_on:
    - zookeeper
networks:
  kafka-network:
    driver: bridge
